/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVER_H_RPCGEN
#define _SERVER_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#define VERNUM 1
#define INITVER 1
#define EXISTVER 2
#define SETVER 3
#define GETVER 4
#define MODIFYVER 5
#define DELETEVER 6

typedef double vector_32[32];

struct tuple {
	int key;
	char *value1;
	int N_value2;
	vector_32 V_value2;
};
typedef struct tuple tuple;

#define server 1
#define VERNUM 1

#if defined(__STDC__) || defined(__cplusplus)
#define init_server INITVER
extern  enum clnt_stat init_server_1(void *, CLIENT *);
extern  bool_t init_server_1_svc(void *, struct svc_req *);
#define exists EXISTVER
extern  enum clnt_stat exists_1(int , int *, CLIENT *);
extern  bool_t exists_1_svc(int , int *, struct svc_req *);
#define set_tuple SETVER
extern  enum clnt_stat set_tuple_1(struct tuple , void *, CLIENT *);
extern  bool_t set_tuple_1_svc(struct tuple , void *, struct svc_req *);
#define get_tuple GETVER
extern  enum clnt_stat get_tuple_1(int , struct tuple *, CLIENT *);
extern  bool_t get_tuple_1_svc(int , struct tuple *, struct svc_req *);
#define modify_tuple MODIFYVER
extern  enum clnt_stat modify_tuple_1(struct tuple , void *, CLIENT *);
extern  bool_t modify_tuple_1_svc(struct tuple , void *, struct svc_req *);
#define delete_tuple DELETEVER
extern  enum clnt_stat delete_tuple_1(int , void *, CLIENT *);
extern  bool_t delete_tuple_1_svc(int , void *, struct svc_req *);
extern int server_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define init_server INITVER
extern  enum clnt_stat init_server_1();
extern  bool_t init_server_1_svc();
#define exists EXISTVER
extern  enum clnt_stat exists_1();
extern  bool_t exists_1_svc();
#define set_tuple SETVER
extern  enum clnt_stat set_tuple_1();
extern  bool_t set_tuple_1_svc();
#define get_tuple GETVER
extern  enum clnt_stat get_tuple_1();
extern  bool_t get_tuple_1_svc();
#define modify_tuple MODIFYVER
extern  enum clnt_stat modify_tuple_1();
extern  bool_t modify_tuple_1_svc();
#define delete_tuple DELETEVER
extern  enum clnt_stat delete_tuple_1();
extern  bool_t delete_tuple_1_svc();
extern int server_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_vector_32 (XDR *, vector_32);
extern  bool_t xdr_tuple (XDR *, tuple*);

#else /* K&R C */
extern bool_t xdr_vector_32 ();
extern bool_t xdr_tuple ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVER_H_RPCGEN */
